### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gabrielferreiraa** [react-brasil/newsletter#3]
Abaixo seguem algumas as tarefas que já foram realizadas e algumas que faltam realizar.

- [x] Landing Page
- [x] Criar aplicação Firebase
- [x] Realizar integração com Firebase
- [x] Adicionar e-mail no Firebase
- [ ] Verificar uma forma de realizar o cancelamento da assinatura
- [x] Montar o HTML do e-mail que será disparado
- [x] Criar canal no Slack para comunidade enviar as noticias
- [x] Criar conta Egoi com e-mail padrão
- [x] Criar mecanismo de obtenção dos e-mails que estão no Firebase [Work in Progress pelo @brunoxd13 ]
- [ ] Criar cloud functions para adicionar usuarios
- [ ] Ajustar `rules` do firestore

**Comment by brunoxd13** [comment]
- [x]  Montar o HTML do e-mail que será disparad.

[model_email.html.zip](https://github.com/react-brasil/newsletter/files/2437838/model_email.html.zip)

**Comment by brunoxd13** [comment]
- [x] Criar conta Egoi com e-mail padrão.

**Comment by brunoxd13** [comment]
- [x] Criar mecanismo de obtenção dos e-mails que estão no Firebase.
